using System;
using System.Collections.Generic;
using System.Text;

namespace DeathMessageAboveCorpse
{
    public static class Quotes
    {
        public static string[] deathMessages = new string[]
        {
            "shak pls.",
            "You are dead.",
            "You embrace the void.",
            "You had a lot more to live for.",
            "Your internal organs have failed.",
            "Your body was gone an hour later.",
            "Your family will never know how you died.",
            "You died painlessly.",
            "Your death was extremely painful.",
            "You have broken every bone in your body.",
            "You die a slightly embarrassing death.",
            "You die in a hilarious pose.",
            "You really messed up.",
            "You have died. Maybe next time..",
            "You have passed away. Try again?",
            "Choose a new character?",
            "Remember to activate use items.",
            "Remember that as time increases, so does difficulty.",
            "This planet has killed you.",
            "It wasn't your time to die...",
            "That was definitely not your fault.",
            "That was absolutely your fault.",
            "They will surely feast on your flesh.",
            "..the harder they fall.",
            "Beep.. beep.. beeeeeeeeeeeeeeeee",
            "Close!",
            "Come back soon!",
            "Crushed.",
            "Smashed.",
            "DEAD",
            "Get styled upon.",
            "Dead from blunt trauma to the face.",
            "ded",
            "rekt",
            "ur dead LOL get rekt",
            "Sucks to suck.",
            "You walk towards the light.",

            // TODO: Seperate based on difficulty (Run.instance.selectedDifficulty)
            "Try playing on \"Drizzle\" mode for an easier time.",
            "Consider lowering the difficulty.",
        };

        public static string[] deathMessagesStarstorm = new string[]
        {"Oh no...",
        "Oopsie.",
        "Should have seen that coming.",
        "Destiny sealed.",
        "That was depressing.",
        "Anticlimatic.",
        "Yeet.",
        "That wasn't cool.",
        "Dying, again.",
        "Could have been worse.",
        "At least you tried.",
        "Heartbroken.",
        "Not OP.",
        "Should have gotten Dio's Friend.",
        "What?",
        "Yeah... nice.",
        "Are you okay?",
        "Let's try again sometime soon.",
        "Rude, didn't even say goodbye.",
        "Another one bites the dust.",
        "Stinky.",
        "Get some rest.",
        "I don't get it.",
        ":(",
        "To be honest, I expected that.",
        "You are no more.",
        "You died painfully.",
        "Let's pretend that didn't happen.",
        "Bye bye.",
        "You cried before losing consciousness.",
        "You will be remembered.",
        "You didn't stand a chance.",
        "Very, very dead.",
        "Sorry mom.",
        "Mom says it's my turn now.",
        "What's the point?",
        "Relatable.",
        "Try harder.",
        "Boom.",
        "ouchies owo",
        "F.",
        "This is the part where you quit.",
        "You weren't strong enough.",
        "Continue?",
        "You have perished.",
        "The planet has claimed your life",
        "You fought valiantly... But to no avail.",
        "You didn't know how to live.",
        "The end.",
        "FIN.",
        "Was that it?",
        "Give up?",
        "The end?",
        "Nooooooooooo!",
        "Good enough.",
        "Fair game.",
        "Need a tutorial?",
        "Help is not coming.",
        "Medic!",
        "C-c-c-combo breaker!",
        "It was fun while it lasted.",
        "An attempt was made.",
        "You had one job.",
        "Good job!",
        "Need a hug?",
        "Hnng.",
        "Life comes and goes.",
        "It's just a game.",
        "You'll win! ...Someday.",
        "You could do it.",
        "dead.exe",
        "Imagine living",
        "What?!",
        "What was that?",
        "Don't skip leg day.",
        "Wow! Okay...",
        "Whew.",
        "Yes, you just died.",
        "Free ticket to hell.",
        "Free ticket to heaven.",
        "The void welcomes you.",
        "Weee wooo weee wooo."
        };
    }
}
